import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, resolve } from "node:path";
import { type BillingConfig, generateOpenApiSpec, generateTrpcRouterCode } from "@guapocado/shared";
import { defineCommand } from "citty";
import consola from "consola";
import { loadBillingConfig } from "../billing-config.js";
import {
	type DrizzleDialect,
	generateDrizzleServerTables,
	normalizeDrizzleDialect,
} from "../generators/drizzle-server.js";

type TableGenerationConfig = NonNullable<NonNullable<BillingConfig["generate"]>["tables"]>;

function generateTypes(config: BillingConfig): string {
	const entitlementKeys = Object.keys(config.entitlements);
	const planKeys = config.products.map((p) => p.key);

	return `// Generated by guap generate — do not edit
export type EntitlementKey =
${entitlementKeys.map((k) => `\t| "${k}"`).join("\n")};

export type ProductKey =
${planKeys.map((k) => `\t| "${k}"`).join("\n")};

/** @deprecated Use ProductKey. */
export type PlanKey = ProductKey;

export type GuapocadoEntitlements = {
${entitlementKeys.map((k) => `\t"${k}": ${config.entitlements[k]?.type === "feature" ? "boolean" : "number"};`).join("\n")}
};
`;
}

function normalizeOrm(value: unknown): "drizzle" | null {
	if (!value) return null;
	const normalized = String(value).trim().toLowerCase();
	return normalized === "drizzle" || normalized === "drizzle-orm" ? "drizzle" : null;
}

function readPackageJson(
	cwd: string,
): { dependencies?: Record<string, string>; devDependencies?: Record<string, string> } | null {
	const path = resolve(cwd, "package.json");
	if (!existsSync(path)) return null;

	try {
		return JSON.parse(readFileSync(path, "utf-8")) as {
			dependencies?: Record<string, string>;
			devDependencies?: Record<string, string>;
		};
	} catch {
		return null;
	}
}

function detectDrizzleDialect(cwd: string): DrizzleDialect | null {
	for (const configName of [
		"drizzle.config.ts",
		"drizzle.config.js",
		"drizzle.config.mjs",
		"drizzle.config.cjs",
	]) {
		const path = resolve(cwd, configName);
		if (!existsSync(path)) continue;
		const contents = readFileSync(path, "utf-8");
		const dialectMatch = contents.match(/dialect\s*:\s*["']([^"']+)["']/);
		const normalized = normalizeDrizzleDialect(dialectMatch?.[1]);
		if (normalized) return normalized;
	}

	const pkg = readPackageJson(cwd);
	const deps = { ...pkg?.dependencies, ...pkg?.devDependencies };
	const dependencyNames = new Set(Object.keys(deps));

	if (
		dependencyNames.has("@libsql/client") ||
		dependencyNames.has("better-sqlite3") ||
		dependencyNames.has("sqlite3")
	) {
		return "sqlite";
	}
	if (
		dependencyNames.has("pg") ||
		dependencyNames.has("postgres") ||
		dependencyNames.has("@neondatabase/serverless")
	) {
		return "pg";
	}
	if (
		dependencyNames.has("mysql2") ||
		dependencyNames.has("mysql") ||
		dependencyNames.has("@planetscale/database")
	) {
		return "mysql";
	}

	return null;
}

function hasCliTableRequest(args: Record<string, unknown>): boolean {
	return Boolean(
		args.tables ||
			args.orm ||
			args.db ||
			args.database ||
			args.dialect ||
			args["table-output"] ||
			args["table-set"],
	);
}

function hasConfigTableRequest(tableConfig: TableGenerationConfig | undefined): boolean {
	if (!tableConfig || tableConfig.enabled === false) return false;
	return Boolean(
		tableConfig.enabled ||
			tableConfig.tableSet ||
			tableConfig.orm ||
			tableConfig.db ||
			tableConfig.output,
	);
}

function shouldGenerateTables(
	args: Record<string, unknown>,
	tableConfig: TableGenerationConfig | undefined,
): boolean {
	return hasCliTableRequest(args) || hasConfigTableRequest(tableConfig);
}

function resolveTableOutput(
	cwd: string,
	outputDir: string,
	tableOutput: unknown,
	dialect: DrizzleDialect,
) {
	const filename = String(tableOutput || `guapocado.drizzle.${dialect}.ts`);
	return isAbsolute(filename) ? filename : resolve(outputDir || cwd, filename);
}

function generateTables(
	cwd: string,
	outputDir: string,
	args: Record<string, unknown>,
	tableConfig: TableGenerationConfig | undefined,
) {
	const tableSet = String(args["table-set"] ?? tableConfig?.tableSet ?? "server")
		.trim()
		.toLowerCase();
	if (tableSet !== "server") {
		throw new Error(`Unsupported table set "${tableSet}". Supported table sets: server.`);
	}

	const ormInput = args.orm ?? tableConfig?.orm ?? "drizzle";
	const orm = normalizeOrm(ormInput);
	if (orm !== "drizzle") {
		throw new Error(`Unsupported ORM "${String(ormInput)}". Supported ORMs: drizzle.`);
	}

	const dialect =
		normalizeDrizzleDialect(
			String(args.db ?? args.database ?? args.dialect ?? tableConfig?.db ?? "").trim() || undefined,
		) ?? detectDrizzleDialect(cwd);

	if (!dialect) {
		throw new Error(
			"Could not detect a Drizzle database dialect. Pass --db sqlite, --db pg, or --db mysql.",
		);
	}

	const outputPath = resolveTableOutput(
		cwd,
		outputDir,
		args["table-output"] ?? tableConfig?.output,
		dialect,
	);
	mkdirSync(dirname(outputPath), { recursive: true });
	writeFileSync(outputPath, generateDrizzleServerTables(dialect), "utf-8");
	consola.success(`Generated ${outputPath.replace(`${cwd}/`, "")}`);
}

export default defineCommand({
	meta: {
		description: "Generate TypeScript types, OpenAPI spec, and tRPC router from billing schema",
	},
	args: {
		output: {
			type: "string",
			description: "Output directory",
			default: ".",
		},
		tables: {
			type: "boolean",
			description: "Generate server SDK database table definitions",
		},
		orm: {
			type: "string",
			description: "ORM target for table definitions. Supported value: drizzle",
		},
		db: {
			type: "string",
			description: "Database dialect for table definitions: sqlite, pg, or mysql",
		},
		database: {
			type: "string",
			description: "Alias for --db",
		},
		dialect: {
			type: "string",
			description: "Alias for --db",
		},
		"table-set": {
			type: "string",
			description: "Table set to generate. Currently supports: server",
		},
		"table-output": {
			type: "string",
			description: "Output filename for generated table definitions",
		},
		config: {
			type: "string",
			alias: "c",
			description: "Path to a billing config file or its directory (default: current directory)",
		},
	},
	async run({ args }) {
		const cwd = process.cwd();
		const outputDir = resolve(cwd, args.output);
		mkdirSync(outputDir, { recursive: true });
		const config = await loadBillingConfig((args.config as string | undefined) ?? cwd);
		const tableConfig = config?.generate?.tables;
		const tableRequested = shouldGenerateTables(args, tableConfig);
		if (!config) {
			if (!tableRequested) {
				consola.error(
					"No Guapocado config found. Expected billing.config.ts, billing.config.json, guapocado.billing.json, or guapocado.billing.yaml.",
				);
				return;
			}
			consola.info("No Guapocado config found; generating database tables only.");
		}

		if (config) {
			const types = generateTypes(config);
			writeFileSync(resolve(outputDir, "billing.generated.ts"), types, "utf-8");
			consola.success("Generated billing.generated.ts");

			const openapi = generateOpenApiSpec(config);
			writeFileSync(
				resolve(outputDir, "billing.openapi.json"),
				JSON.stringify(openapi, null, "\t"),
				"utf-8",
			);
			consola.success("Generated billing.openapi.json");

			const trpcRouter = generateTrpcRouterCode(config);
			writeFileSync(resolve(outputDir, "billing.router.ts"), trpcRouter, "utf-8");
			consola.success("Generated billing.router.ts");
		}

		if (tableRequested) {
			generateTables(cwd, outputDir, args, tableConfig);
		}
	},
});
