import type { BillingConfig } from "./schema.js";

/** Serializable description of generated tRPC procedures for a billing config. */
export type TrpcRouterDefinition = {
	procedures: {
		name: string;
		type: "query" | "mutation";
		path: string;
		input?: Record<string, unknown>;
	}[];
};

/**
 * Builds a serializable, data-only manifest of the tRPC procedures (entitlement
 * checks, usage operations, checkout, and listings) that a billing config
 * exposes, with each procedure's name, query/mutation type, dotted path, and
 * input shape — without emitting any TypeScript source.
 *
 * @param config The billing config whose entitlement and product keys constrain the generated procedure inputs.
 * @returns A {@link TrpcRouterDefinition} listing every generated procedure and its metadata.
 * @example
 * ```ts
 * import { generateTrpcRouterDefinition } from "@guapocado/shared";
 *
 * const { procedures } = generateTrpcRouterDefinition(config);
 * const mutations = procedures.filter((p) => p.type === "mutation");
 * ```
 */
export function generateTrpcRouterDefinition(config: BillingConfig): TrpcRouterDefinition {
	const entitlementKeys = Object.keys(config.entitlements);

	const procedures: TrpcRouterDefinition["procedures"] = [
		{
			name: "hasEntitlement",
			type: "query",
			path: "guap.entitlements.has",
			input: { key: { type: "string", enum: entitlementKeys }, customerId: { type: "string" } },
		},
		{
			name: "getLimit",
			type: "query",
			path: "guap.entitlements.limit",
			input: { key: { type: "string", enum: entitlementKeys }, customerId: { type: "string" } },
		},
		{
			name: "configureLimit",
			type: "mutation",
			path: "guap.entitlements.configureLimit",
			input: {
				key: { type: "string", enum: entitlementKeys },
				customerId: { type: "string" },
				purchased: { type: "number" },
				autoExpansionEnabled: { type: "boolean" },
			},
		},
		{
			name: "consume",
			type: "mutation",
			path: "guap.usage.consume",
			input: {
				key: { type: "string", enum: entitlementKeys },
				customerId: { type: "string" },
				amount: { type: "number" },
			},
		},
		{
			name: "configureUsage",
			type: "mutation",
			path: "guap.usage.configure",
			input: {
				key: { type: "string", enum: entitlementKeys },
				customerId: { type: "string" },
				overageEnabled: { type: "boolean" },
			},
		},
		{
			name: "createCheckout",
			type: "mutation",
			path: "guap.checkout.create",
			input: {
				productKey: { type: "string", enum: config.products.map((p) => p.key) },
				planKey: {
					type: "string",
					enum: config.products.map((p) => p.key),
					deprecated: true,
				},
				customerId: { type: "string" },
				successUrl: { type: "string" },
				cancelUrl: { type: "string" },
			},
		},
		{
			name: "listCustomers",
			type: "query",
			path: "guap.customers.list",
		},
		{
			name: "listSubscriptions",
			type: "query",
			path: "guap.subscriptions.list",
			input: { customerId: { type: "string" } },
		},
		{
			name: "listPurchases",
			type: "query",
			path: "guap.purchases.list",
			input: { customerId: { type: "string" } },
		},
	];

	return { procedures };
}

/**
 * Generates ready-to-write TypeScript source for a tRPC router backed by the
 * Guapocado SDK, embedding the config's entitlement and product keys as Zod
 * enums and wiring entitlement, usage, and checkout procedures to the SDK client
 * — this is what `guap generate` writes to disk.
 *
 * @param config The billing config whose entitlement and product keys are baked into the generated Zod schemas and router.
 * @returns A string of TypeScript source defining a `createGuapocadoRouter` factory, suitable for writing to a `.ts` file.
 * @example
 * ```ts
 * import { generateTrpcRouterCode } from "@guapocado/shared";
 *
 * const source = generateTrpcRouterCode(config);
 * await writeFile("src/server/guap-router.ts", source);
 * ```
 */
export function generateTrpcRouterCode(config: BillingConfig): string {
	const entitlementKeys = Object.keys(config.entitlements);
	const productKeys = config.products.map((p) => p.key);

	return `// Generated by guap generate — do not edit
import { z } from "zod";
import { createGuapocadoClient } from "@guapocado/sdk";

const entitlementKeySchema = z.enum([${entitlementKeys.map((k) => `"${k}"`).join(", ")}]);
const productKeySchema = z.enum([${productKeys.map((k) => `"${k}"`).join(", ")}]);

export function createGuapocadoRouter(t: { router: Function; procedure: any }, apiKey: string) {
\tconst guap = createGuapocadoClient({ apiKey });

\treturn t.router({
\t\tentitlements: t.router({
\t\t\thas: t.procedure
\t\t\t\t.input(z.object({ key: entitlementKeySchema, customerId: z.string() }))
\t\t\t\t.query(({ input }) => guap.has(input.key, { customerId: input.customerId })),
\t\t\tlimit: t.procedure
\t\t\t\t.input(z.object({ key: entitlementKeySchema, customerId: z.string() }))
\t\t\t\t.query(({ input }) => guap.limit(input.key, { customerId: input.customerId })),
\t\t\tconfigureLimit: t.procedure
\t\t\t\t.input(z.object({ key: entitlementKeySchema, customerId: z.string(), purchased: z.number(), autoExpansionEnabled: z.boolean() }))
\t\t\t\t.mutation(({ input }) => guap.limits.configure(input.key, { purchased: input.purchased, autoExpansionEnabled: input.autoExpansionEnabled }, { customerId: input.customerId })),
\t\t}),
\t\tusage: t.router({
\t\t\tbalance: t.procedure
\t\t\t\t.input(z.object({ key: entitlementKeySchema, customerId: z.string() }))
\t\t\t\t.query(({ input }) => guap.usage.balance(input.key, { customerId: input.customerId })),
\t\t\tconsume: t.procedure
\t\t\t\t.input(z.object({ key: entitlementKeySchema, customerId: z.string(), amount: z.number() }))
\t\t\t\t.mutation(({ input }) => guap.usage.consume(input.key, input.amount, { customerId: input.customerId })),
\t\t\trefund: t.procedure
\t\t\t\t.input(z.object({ key: entitlementKeySchema, customerId: z.string(), amount: z.number() }))
\t\t\t\t.mutation(({ input }) => guap.usage.refund(input.key, input.amount, { customerId: input.customerId })),
\t\t\tconfigure: t.procedure
\t\t\t\t.input(z.object({ key: entitlementKeySchema, customerId: z.string(), overageEnabled: z.boolean() }))
\t\t\t\t.mutation(({ input }) => guap.usage.configure(input.key, { overageEnabled: input.overageEnabled }, { customerId: input.customerId })),
\t\t}),
\t});
}
`;
}
